import type { Confidence, RunDetail } from "@/lib/gateway";

const confidenceLabel: Record<Confidence, string> = {
  high: "high confidence",
  mid: "medium confidence",
  low: "low confidence",
};

const metricLabel: Record<string, string> = {
  grounding: "Grounding",
  source_quality: "Source quality",
  consistency: "Consistency",
  corroboration: "Corroboration",
};

/**
 * Renders a completed run as a self-contained, cited Markdown report. Pure and
 * deterministic so it is trivially testable and identical every export.
 */
export function buildMarkdownReport(run: RunDetail, generatedAt = new Date()): string {
  const lines: string[] = [];

  lines.push(`# ${run.question}`, "");
  lines.push(
    `*Generated by Consilience on ${generatedAt.toISOString().slice(0, 10)}. ` +
      `Research is AI-generated and may contain errors — verify each claim against its ` +
      `cited sources before relying on it.*`,
    "",
  );

  if (run.summary) {
    lines.push("## Summary", "", run.summary, "");
  }

  if (run.evaluations.length > 0) {
    lines.push("## Evaluation", "");
    for (const e of run.evaluations) {
      lines.push(`- ${metricLabel[e.metric] ?? e.metric}: ${Math.round(e.score * 100)}%`);
    }
    lines.push("");
  }

  lines.push(`## Claims (${run.claims.length})`, "");
  for (const c of run.claims) {
    const cites = c.sourcePositions.map((p) => `[${p}]`).join("");
    const agent = c.agent ? `, ${c.agent}` : "";
    lines.push(`${c.position}. ${c.text} _(${confidenceLabel[c.confidence]}${agent})_ ${cites}`.trim());
  }
  lines.push("");

  if (run.contradictions.length > 0) {
    lines.push(`## Contradictions (${run.contradictions.length})`, "");
    for (const x of run.contradictions) {
      lines.push(`- Between claims [${x.claimA}] and [${x.claimB}]: ${x.explanation}`);
    }
    lines.push("");
  }

  lines.push(`## Sources (${run.sources.length})`, "");
  for (const s of run.sources) {
    const cred = s.credibility ? ` _(${s.credibility} credibility)_` : "";
    lines.push(`${s.position}. ${s.title || s.url} — ${s.url}${cred}`);
  }
  lines.push("");

  return lines.join("\n");
}

export function reportFilename(run: RunDetail): string {
  const slug = run.question
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return `consilience-${slug || "report"}.md`;
}
